
package oasis.names.tc.wsrp.v1.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */

@WebFault(name = "AccessDenied", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")

public class AccessDenied extends Exception {
    public static final long serialVersionUID = 20080813152222L;
    
    private oasis.names.tc.wsrp.v1.types.AccessDeniedFault accessDenied;

    public AccessDenied() {
        super();
    }
    
    public AccessDenied(String message) {
        super(message);
    }
    
    public AccessDenied(String message, Throwable cause) {
        super(message, cause);
    }

    public AccessDenied(String message, oasis.names.tc.wsrp.v1.types.AccessDeniedFault accessDenied) {
        super(message);
        this.accessDenied = accessDenied;
    }

    public AccessDenied(String message, oasis.names.tc.wsrp.v1.types.AccessDeniedFault accessDenied, Throwable cause) {
        super(message, cause);
        this.accessDenied = accessDenied;
    }

    public oasis.names.tc.wsrp.v1.types.AccessDeniedFault getFaultInfo() {
        return this.accessDenied;
    }
}
