
package oasis.names.tc.wsrp.v1.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */

@WebFault(name = "InvalidCookie", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")

public class InvalidCookie extends Exception {
    public static final long serialVersionUID = 20080813152222L;
    
    private oasis.names.tc.wsrp.v1.types.InvalidCookieFault invalidCookie;

    public InvalidCookie() {
        super();
    }
    
    public InvalidCookie(String message) {
        super(message);
    }
    
    public InvalidCookie(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCookie(String message, oasis.names.tc.wsrp.v1.types.InvalidCookieFault invalidCookie) {
        super(message);
        this.invalidCookie = invalidCookie;
    }

    public InvalidCookie(String message, oasis.names.tc.wsrp.v1.types.InvalidCookieFault invalidCookie, Throwable cause) {
        super(message, cause);
        this.invalidCookie = invalidCookie;
    }

    public oasis.names.tc.wsrp.v1.types.InvalidCookieFault getFaultInfo() {
        return this.invalidCookie;
    }
}
