
package oasis.names.tc.wsrp.v1.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */

@WebFault(name = "InvalidUserCategory", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")

public class InvalidUserCategory extends Exception {
    public static final long serialVersionUID = 20080813152222L;
    
    private oasis.names.tc.wsrp.v1.types.InvalidUserCategoryFault invalidUserCategory;

    public InvalidUserCategory() {
        super();
    }
    
    public InvalidUserCategory(String message) {
        super(message);
    }
    
    public InvalidUserCategory(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidUserCategory(String message, oasis.names.tc.wsrp.v1.types.InvalidUserCategoryFault invalidUserCategory) {
        super(message);
        this.invalidUserCategory = invalidUserCategory;
    }

    public InvalidUserCategory(String message, oasis.names.tc.wsrp.v1.types.InvalidUserCategoryFault invalidUserCategory, Throwable cause) {
        super(message, cause);
        this.invalidUserCategory = invalidUserCategory;
    }

    public oasis.names.tc.wsrp.v1.types.InvalidUserCategoryFault getFaultInfo() {
        return this.invalidUserCategory;
    }
}
