
package oasis.names.tc.wsrp.v1.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */

@WebFault(name = "InvalidSession", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")

public class InvalidSession extends Exception {
    public static final long serialVersionUID = 20080813152222L;
    
    private oasis.names.tc.wsrp.v1.types.InvalidSessionFault invalidSession;

    public InvalidSession() {
        super();
    }
    
    public InvalidSession(String message) {
        super(message);
    }
    
    public InvalidSession(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidSession(String message, oasis.names.tc.wsrp.v1.types.InvalidSessionFault invalidSession) {
        super(message);
        this.invalidSession = invalidSession;
    }

    public InvalidSession(String message, oasis.names.tc.wsrp.v1.types.InvalidSessionFault invalidSession, Throwable cause) {
        super(message, cause);
        this.invalidSession = invalidSession;
    }

    public oasis.names.tc.wsrp.v1.types.InvalidSessionFault getFaultInfo() {
        return this.invalidSession;
    }
}
