
package oasis.names.tc.wsrp.v1.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */

@WebFault(name = "InvalidHandle", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")

public class InvalidHandle extends Exception {
    public static final long serialVersionUID = 20080813152222L;
    
    private oasis.names.tc.wsrp.v1.types.InvalidHandleFault invalidHandle;

    public InvalidHandle() {
        super();
    }
    
    public InvalidHandle(String message) {
        super(message);
    }
    
    public InvalidHandle(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidHandle(String message, oasis.names.tc.wsrp.v1.types.InvalidHandleFault invalidHandle) {
        super(message);
        this.invalidHandle = invalidHandle;
    }

    public InvalidHandle(String message, oasis.names.tc.wsrp.v1.types.InvalidHandleFault invalidHandle, Throwable cause) {
        super(message, cause);
        this.invalidHandle = invalidHandle;
    }

    public oasis.names.tc.wsrp.v1.types.InvalidHandleFault getFaultInfo() {
        return this.invalidHandle;
    }
}
