
package oasis.names.tc.wsrp.v1.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */

@WebFault(name = "MissingParameters", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")

public class MissingParameters extends Exception {
    public static final long serialVersionUID = 20080813152222L;
    
    private oasis.names.tc.wsrp.v1.types.MissingParametersFault missingParameters;

    public MissingParameters() {
        super();
    }
    
    public MissingParameters(String message) {
        super(message);
    }
    
    public MissingParameters(String message, Throwable cause) {
        super(message, cause);
    }

    public MissingParameters(String message, oasis.names.tc.wsrp.v1.types.MissingParametersFault missingParameters) {
        super(message);
        this.missingParameters = missingParameters;
    }

    public MissingParameters(String message, oasis.names.tc.wsrp.v1.types.MissingParametersFault missingParameters, Throwable cause) {
        super(message, cause);
        this.missingParameters = missingParameters;
    }

    public oasis.names.tc.wsrp.v1.types.MissingParametersFault getFaultInfo() {
        return this.missingParameters;
    }
}
