
package oasis.names.tc.wsrp.v1.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */

@WebFault(name = "OperationFailed", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")

public class OperationFailed extends Exception {
    public static final long serialVersionUID = 20080813152222L;
    
    private oasis.names.tc.wsrp.v1.types.OperationFailedFault operationFailed;

    public OperationFailed() {
        super();
    }
    
    public OperationFailed(String message) {
        super(message);
    }
    
    public OperationFailed(String message, Throwable cause) {
        super(message, cause);
    }

    public OperationFailed(String message, oasis.names.tc.wsrp.v1.types.OperationFailedFault operationFailed) {
        super(message);
        this.operationFailed = operationFailed;
    }

    public OperationFailed(String message, oasis.names.tc.wsrp.v1.types.OperationFailedFault operationFailed, Throwable cause) {
        super(message, cause);
        this.operationFailed = operationFailed;
    }

    public oasis.names.tc.wsrp.v1.types.OperationFailedFault getFaultInfo() {
        return this.operationFailed;
    }
}
