
package oasis.names.tc.wsrp.v1.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */

@WebFault(name = "PortletStateChangeRequired", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")

public class PortletStateChangeRequired extends Exception {
    public static final long serialVersionUID = 20080813152222L;
    
    private oasis.names.tc.wsrp.v1.types.PortletStateChangeRequiredFault portletStateChangeRequired;

    public PortletStateChangeRequired() {
        super();
    }
    
    public PortletStateChangeRequired(String message) {
        super(message);
    }
    
    public PortletStateChangeRequired(String message, Throwable cause) {
        super(message, cause);
    }

    public PortletStateChangeRequired(String message, oasis.names.tc.wsrp.v1.types.PortletStateChangeRequiredFault portletStateChangeRequired) {
        super(message);
        this.portletStateChangeRequired = portletStateChangeRequired;
    }

    public PortletStateChangeRequired(String message, oasis.names.tc.wsrp.v1.types.PortletStateChangeRequiredFault portletStateChangeRequired, Throwable cause) {
        super(message, cause);
        this.portletStateChangeRequired = portletStateChangeRequired;
    }

    public oasis.names.tc.wsrp.v1.types.PortletStateChangeRequiredFault getFaultInfo() {
        return this.portletStateChangeRequired;
    }
}
