
package oasis.names.tc.wsrp.v1.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */

@WebFault(name = "UnsupportedLocale", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")

public class UnsupportedLocale extends Exception {
    public static final long serialVersionUID = 20080813152222L;
    
    private oasis.names.tc.wsrp.v1.types.UnsupportedLocaleFault unsupportedLocale;

    public UnsupportedLocale() {
        super();
    }
    
    public UnsupportedLocale(String message) {
        super(message);
    }
    
    public UnsupportedLocale(String message, Throwable cause) {
        super(message, cause);
    }

    public UnsupportedLocale(String message, oasis.names.tc.wsrp.v1.types.UnsupportedLocaleFault unsupportedLocale) {
        super(message);
        this.unsupportedLocale = unsupportedLocale;
    }

    public UnsupportedLocale(String message, oasis.names.tc.wsrp.v1.types.UnsupportedLocaleFault unsupportedLocale, Throwable cause) {
        super(message, cause);
        this.unsupportedLocale = unsupportedLocale;
    }

    public oasis.names.tc.wsrp.v1.types.UnsupportedLocaleFault getFaultInfo() {
        return this.unsupportedLocale;
    }
}
