
package oasis.names.tc.wsrp.v1.intf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */

@WebFault(name = "UnsupportedMimeType", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")

public class UnsupportedMimeType extends Exception {
    public static final long serialVersionUID = 20080813152222L;
    
    private oasis.names.tc.wsrp.v1.types.UnsupportedMimeTypeFault unsupportedMimeType;

    public UnsupportedMimeType() {
        super();
    }
    
    public UnsupportedMimeType(String message) {
        super(message);
    }
    
    public UnsupportedMimeType(String message, Throwable cause) {
        super(message, cause);
    }

    public UnsupportedMimeType(String message, oasis.names.tc.wsrp.v1.types.UnsupportedMimeTypeFault unsupportedMimeType) {
        super(message);
        this.unsupportedMimeType = unsupportedMimeType;
    }

    public UnsupportedMimeType(String message, oasis.names.tc.wsrp.v1.types.UnsupportedMimeTypeFault unsupportedMimeType, Throwable cause) {
        super(message, cause);
        this.unsupportedMimeType = unsupportedMimeType;
    }

    public oasis.names.tc.wsrp.v1.types.UnsupportedMimeTypeFault getFaultInfo() {
        return this.unsupportedMimeType;
    }
}
