
/*
 * 
 */

package oasis.names.tc.wsrp.v1.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */
 
 /*
  * 
  */


@WebService(targetNamespace = "urn:oasis:names:tc:wsrp:v1:intf", name = "WSRP_v1_ServiceDescription_PortType")
@XmlSeeAlso({oasis.names.tc.wsrp.v1.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface WSRPV1ServiceDescriptionPortType {

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getServiceDescriptionResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "getServiceDescriptionResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:getServiceDescription")
    public oasis.names.tc.wsrp.v1.types.ServiceDescription getServiceDescription(
        @WebParam(partName = "getServiceDescription", name = "getServiceDescription", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.GetServiceDescription getServiceDescription
    ) throws InvalidRegistration, OperationFailed;
}
