
/*
 * 
 */

package oasis.names.tc.wsrp.v1.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */
 
 /*
  * 
  */


@WebService(targetNamespace = "urn:oasis:names:tc:wsrp:v1:intf", name = "WSRP_v1_Registration_PortType")
@XmlSeeAlso({oasis.names.tc.wsrp.v1.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface WSRPV1RegistrationPortType {

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "modifyRegistrationResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "modifyRegistrationResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:modifyRegistration")
    public oasis.names.tc.wsrp.v1.types.RegistrationState modifyRegistration(
        @WebParam(partName = "modifyRegistration", name = "modifyRegistration", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.ModifyRegistration modifyRegistration
    ) throws InvalidRegistration, MissingParameters, OperationFailed;

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "deregisterResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "deregisterResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:deregister")
    public oasis.names.tc.wsrp.v1.types.ReturnAny deregister(
        @WebParam(partName = "deregister", name = "deregister", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.RegistrationContext deregister
    ) throws InvalidRegistration, OperationFailed;

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "registerResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "registerResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:register")
    public oasis.names.tc.wsrp.v1.types.RegistrationContext register(
        @WebParam(partName = "register", name = "register", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.RegistrationData register
    ) throws MissingParameters, OperationFailed;
}
