
/*
 * 
 */

package oasis.names.tc.wsrp.v1.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */
 
 /*
  * 
  */


@WebService(targetNamespace = "urn:oasis:names:tc:wsrp:v1:intf", name = "WSRP_v1_PortletManagement_PortType")
@XmlSeeAlso({oasis.names.tc.wsrp.v1.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface WSRPV1PortletManagementPortType {

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "destroyPortletsResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "destroyPortletsResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:destroyPortlets")
    public oasis.names.tc.wsrp.v1.types.DestroyPortletsResponse destroyPortlets(
        @WebParam(partName = "destroyPortlets", name = "destroyPortlets", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.DestroyPortlets destroyPortlets
    ) throws InvalidRegistration, MissingParameters, InconsistentParameters, OperationFailed;

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "setPortletPropertiesResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "setPortletPropertiesResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:setPortletProperties")
    public oasis.names.tc.wsrp.v1.types.PortletContext setPortletProperties(
        @WebParam(partName = "setPortletProperties", name = "setPortletProperties", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.SetPortletProperties setPortletProperties
    ) throws InvalidRegistration, MissingParameters, InvalidUserCategory, AccessDenied, InvalidHandle, InconsistentParameters, OperationFailed;

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "clonePortletResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "clonePortletResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:clonePortlet")
    public oasis.names.tc.wsrp.v1.types.PortletContext clonePortlet(
        @WebParam(partName = "clonePortlet", name = "clonePortlet", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.ClonePortlet clonePortlet
    ) throws InvalidRegistration, MissingParameters, InvalidUserCategory, AccessDenied, InvalidHandle, InconsistentParameters, OperationFailed;

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getPortletDescriptionResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "getPortletDescriptionResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:getPortletDescription")
    public oasis.names.tc.wsrp.v1.types.PortletDescriptionResponse getPortletDescription(
        @WebParam(partName = "getPortletDescription", name = "getPortletDescription", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.GetPortletDescription getPortletDescription
    ) throws InvalidRegistration, MissingParameters, InvalidUserCategory, AccessDenied, InvalidHandle, InconsistentParameters, OperationFailed;

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getPortletPropertyDescriptionResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "getPortletPropertyDescriptionResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:getPortletPropertyDescription")
    public oasis.names.tc.wsrp.v1.types.PortletPropertyDescriptionResponse getPortletPropertyDescription(
        @WebParam(partName = "getPortletPropertyDescription", name = "getPortletPropertyDescription", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.GetPortletPropertyDescription getPortletPropertyDescription
    ) throws InvalidRegistration, MissingParameters, InvalidUserCategory, AccessDenied, InvalidHandle, InconsistentParameters, OperationFailed;

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getPortletPropertiesResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "getPortletPropertiesResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:getPortletProperties")
    public oasis.names.tc.wsrp.v1.types.PropertyList getPortletProperties(
        @WebParam(partName = "getPortletProperties", name = "getPortletProperties", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.GetPortletProperties getPortletProperties
    ) throws InvalidRegistration, MissingParameters, InvalidUserCategory, AccessDenied, InvalidHandle, InconsistentParameters, OperationFailed;
}
