
package oasis.names.tc.wsrp.v1.intf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import oasis.names.tc.wsrp.v1.wsdl.WSRPService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */

public final class WSRPV1ServiceDescriptionPortType_WSRPServiceDescriptionService_Client {

    private static final QName SERVICE_NAME = new QName("urn:oasis:names:tc:wsrp:v1:wsdl", "WSRPService");

    private WSRPV1ServiceDescriptionPortType_WSRPServiceDescriptionService_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WSRPService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSRPService ss = new WSRPService(wsdlURL, SERVICE_NAME);
        WSRPV1ServiceDescriptionPortType port = ss.getWSRPServiceDescriptionService();  
        
        {
        System.out.println("Invoking getServiceDescription...");
        oasis.names.tc.wsrp.v1.types.GetServiceDescription _getServiceDescription_getServiceDescription = null;
        try {
            oasis.names.tc.wsrp.v1.types.ServiceDescription _getServiceDescription__return = port.getServiceDescription(_getServiceDescription_getServiceDescription);
            System.out.println("getServiceDescription.result=" + _getServiceDescription__return);

        } catch (InvalidRegistration e) { 
            System.out.println("Expected exception: InvalidRegistration has occurred.");
            System.out.println(e.toString());
        } catch (OperationFailed e) { 
            System.out.println("Expected exception: OperationFailed has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
