
/*
 * 
 */

package oasis.names.tc.wsrp.v1.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.1
 * Wed Aug 13 15:22:22 CEST 2008
 * Generated source version: 2.1.1
 * 
 */
 
 /*
  * 
  */


@WebService(targetNamespace = "urn:oasis:names:tc:wsrp:v1:intf", name = "WSRP_v1_Markup_PortType")
@XmlSeeAlso({oasis.names.tc.wsrp.v1.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface WSRPV1MarkupPortType {

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "releaseSessionsResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "releaseSessionsResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:releaseSessions")
    public oasis.names.tc.wsrp.v1.types.ReturnAny releaseSessions(
        @WebParam(partName = "releaseSessions", name = "releaseSessions", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.ReleaseSessions releaseSessions
    ) throws InvalidRegistration, MissingParameters, AccessDenied, OperationFailed;

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getMarkupResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "getMarkupResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:getMarkup")
    public oasis.names.tc.wsrp.v1.types.MarkupResponse getMarkup(
        @WebParam(partName = "getMarkup", name = "getMarkup", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.GetMarkup getMarkup
    ) throws UnsupportedLocale, InvalidRegistration, InvalidUserCategory, UnsupportedMimeType, MissingParameters, InvalidCookie, AccessDenied, InvalidHandle, UnsupportedMode, InvalidSession, UnsupportedWindowState, InconsistentParameters, OperationFailed;

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "initCookieResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "initCookieResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:initCookie")
    public oasis.names.tc.wsrp.v1.types.ReturnAny initCookie(
        @WebParam(partName = "initCookie", name = "initCookie", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.InitCookie initCookie
    ) throws InvalidRegistration, AccessDenied, OperationFailed;

/*
 * 
 */

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "performBlockingInteractionResponse", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types", partName = "performBlockingInteractionResponse")
    @WebMethod(action = "urn:oasis:names:tc:wsrp:v1:performBlockingInteraction")
    public oasis.names.tc.wsrp.v1.types.BlockingInteractionResponse performBlockingInteraction(
        @WebParam(partName = "performBlockingInteraction", name = "performBlockingInteraction", targetNamespace = "urn:oasis:names:tc:wsrp:v1:types")
        oasis.names.tc.wsrp.v1.types.PerformBlockingInteraction performBlockingInteraction
    ) throws UnsupportedLocale, InvalidRegistration, InvalidUserCategory, UnsupportedMimeType, MissingParameters, InvalidCookie, AccessDenied, InvalidHandle, UnsupportedMode, PortletStateChangeRequired, InvalidSession, UnsupportedWindowState, InconsistentParameters, OperationFailed;
}
